[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "python_condor"
version = "0.0.2"
authors = [{ name = "Jiuhong Sun", email = "jiu.hong.sun@gmail.com" }]
dependencies = ["cryptography", "ecdsa", "requests", "result"]
description = "condor python package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://xxx"
Issue = "https://xxx"
